name: xferbench
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - accelerate=0.23.0
  - black=23.9.1
  - datasets=2.14.5
  - evaluate=0.4.0
  - joblib=1.3.2
  - matplotlib=3.8.1
  - mypy=1.6.0
  - pandas-stubs=2.1.1.230928
  - pandas=2.1.1
  - pydantic=2.4.2
  - pytest=8.2.2
  - python=3.11.6
  - pytorch-cuda=12.1
  - pytorch=2.1.0
  - sacrebleu=2.3.1
  - scipy=1.11.3
  - tensorboard=2.14.1
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - transformers=4.34.0
  - zstandard=0.22.0
